"""Write a DDDModel to Neo4j using the UKP graph schema, and export markdown artifacts."""
from __future__ import annotations

import uuid
from pathlib import Path
from typing import Any

from rich.console import Console

from phases.phase1_analysis.ddd_extractor import DDDModel

console = Console()

_MD_HEADER = "<!-- generated by legacy-modernizer — do not edit by hand -->\n\n"


class Neo4jWriter:
    def __init__(self, driver, project_name: str):
        self.driver = driver
        self.project = project_name
        self.entity_id_map: dict[str, str] = {}

    # ── Public API ─────────────────────────────────────────────────────────────

    def write(self, model: DDDModel) -> dict[str, str]:
        console.print("  Writing DDD model to Neo4j...")
        with self.driver.session() as s:
            self._clear_project(s)
            self._write_value_streams(s, model.value_streams)
            self._write_capabilities(s, model.capabilities)
            self._write_value_stream_capabilities(s, model.value_streams, model.capabilities)
            self._write_domains(s, model.domains)
            self._write_subdomains(s, model.subdomains)
            self._write_bounded_contexts(s, model.bounded_contexts)
            self._write_components(s, model.components)
            self._write_contracts(s, model.contracts)
            self._write_jms_queues(s, model.jms_queues)
            self._write_interfaces(s, model.interfaces)
        console.print(
            f"  Neo4j: [green]{len(self.entity_id_map)} nodes written[/green] for project '{self.project}'"
        )
        return self.entity_id_map

    def write_markdown_artifacts(self, model: DDDModel, output_dir: Path):
        ddd_dir = output_dir / "ddd"
        ddd_dir.mkdir(parents=True, exist_ok=True)
        arch_dir = output_dir / "architecture"
        arch_dir.mkdir(parents=True, exist_ok=True)

        self._write_value_streams_md(model, ddd_dir)
        self._write_domains_md(model, ddd_dir)
        self._write_capabilities_md(model, ddd_dir)
        self._write_bounded_contexts_md(model, ddd_dir)
        self._write_components_md(model, ddd_dir)
        self._write_contracts_md(model, ddd_dir)
        self._write_jms_topology_md(model, arch_dir)
        self._write_ubiquitous_language_md(model, ddd_dir)
        console.print(f"  Markdown artifacts written to [cyan]{output_dir}[/cyan]")

    def write_gaps_file(self, model: DDDModel, output_dir: Path):
        gaps_dir = output_dir / "gaps"
        gaps_dir.mkdir(parents=True, exist_ok=True)
        self._write_gaps_md(model, gaps_dir)
        self._write_decisions_md(model, gaps_dir)
        console.print(f"  Gap files written to [cyan]{gaps_dir}[/cyan]")

    # ── Neo4j write helpers ───────────────────────────────────────────────────

    def _eid(self, name: str) -> str:
        if name not in self.entity_id_map:
            self.entity_id_map[name] = str(uuid.uuid4())
        return self.entity_id_map[name]

    def _clear_project(self, s):
        s.run("MATCH (n {project: $p}) DETACH DELETE n", p=self.project)

    def _write_value_streams(self, s, items: list[dict]):
        for v in items:
            s.run(
                "MERGE (n:ValueStream {entityId:$eid}) "
                "SET n.name=$name, n.description=$desc, n.project=$p",
                eid=self._eid(v["name"]), name=v["name"],
                desc=v.get("description", ""), p=self.project,
            )

    def _write_capabilities(self, s, items: list[dict]):
        for c in items:
            s.run(
                "MERGE (n:Capability {entityId:$eid}) "
                "SET n.name=$name, n.level=$level, n.description=$desc, n.project=$p",
                eid=self._eid(c["name"]), name=c["name"],
                level=c.get("level", "L1"), desc=c.get("description", ""), p=self.project,
            )
        for c in items:
            if c.get("parent"):
                s.run(
                    "MATCH (p:Capability {name:$pn, project:$proj}), "
                    "(c:Capability {name:$cn, project:$proj}) "
                    "MERGE (p)-[:HAS_CHILD]->(c)",
                    pn=c["parent"], cn=c["name"], proj=self.project,
                )

    def _write_value_stream_capabilities(self, s, vstreams: list[dict], caps: list[dict]):
        # Link value streams to L1 capabilities
        for cap in caps:
            if cap.get("level") == "L1":
                for vs in vstreams:
                    s.run(
                        "MATCH (v:ValueStream {name:$vn, project:$p}), "
                        "(c:Capability {name:$cn, project:$p}) "
                        "MERGE (v)-[:INVESTS_IN]->(c)",
                        vn=vs["name"], cn=cap["name"], p=self.project,
                    )

    def _write_domains(self, s, items: list[dict]):
        for d in items:
            s.run(
                "MERGE (n:Domain {entityId:$eid}) "
                "SET n.name=$name, n.description=$desc, n.project=$p",
                eid=self._eid(d["name"]), name=d["name"],
                desc=d.get("description", ""), p=self.project,
            )

    def _write_subdomains(self, s, items: list[dict]):
        for sd in items:
            s.run(
                "MERGE (n:Subdomain {entityId:$eid}) "
                "SET n.name=$name, n.description=$desc, n.subdomain_type=$t, n.project=$p",
                eid=self._eid(sd["name"]), name=sd["name"],
                desc=sd.get("description", ""),
                t=sd.get("type", "supporting"), p=self.project,
            )
            if sd.get("domain"):
                s.run(
                    "MATCH (d:Domain {name:$dn, project:$p}), "
                    "(sd:Subdomain {name:$sn, project:$p}) "
                    "MERGE (d)-[:CONTAINS]->(sd)",
                    dn=sd["domain"], sn=sd["name"], p=self.project,
                )

    def _write_bounded_contexts(self, s, items: list[dict]):
        for bc in items:
            s.run(
                "MERGE (n:BoundedContext {entityId:$eid}) "
                "SET n.name=$name, n.description=$desc, "
                "n.ubiquitous_language=$ul, n.key_terms=$kt, n.project=$p",
                eid=self._eid(bc["name"]), name=bc["name"],
                desc=bc.get("description", ""),
                ul=bc.get("ubiquitous_language", ""),
                kt=", ".join(bc.get("key_terms", [])),
                p=self.project,
            )
            if bc.get("subdomain"):
                s.run(
                    "MATCH (sd:Subdomain {name:$sn, project:$p}), "
                    "(bc:BoundedContext {name:$bn, project:$p}) "
                    "MERGE (sd)-[:CONTAINS]->(bc)",
                    sn=bc["subdomain"], bn=bc["name"], p=self.project,
                )

    def _write_components(self, s, items: list[dict]):
        for comp in items:
            s.run(
                "MERGE (n:Component {entityId:$eid}) "
                "SET n.name=$name, n.type=$t, n.description=$desc, "
                "n.jms_role=$jms, n.project=$p",
                eid=self._eid(comp["name"]), name=comp["name"],
                t=comp.get("type", "service"), desc=comp.get("description", ""),
                jms=comp.get("jms_role", ""), p=self.project,
            )
            if comp.get("context"):
                s.run(
                    "MATCH (c:Component {name:$cn, project:$p}), "
                    "(bc:BoundedContext {name:$bn, project:$p}) "
                    "MERGE (c)-[:IMPLEMENTS]->(bc)",
                    cn=comp["name"], bn=comp["context"], p=self.project,
                )
            for dep in comp.get("depends_on", []):
                s.run(
                    "MATCH (a:Component {name:$an, project:$p}), "
                    "(b:Component {name:$bn, project:$p}) "
                    "MERGE (a)-[:DEPENDS_ON]->(b)",
                    an=comp["name"], bn=dep, p=self.project,
                )

    def _write_contracts(self, s, items: list[dict]):
        for ct in items:
            s.run(
                "MERGE (n:Contract {entityId:$eid}) "
                "SET n.name=$name, n.type=$t, n.description=$desc, n.project=$p",
                eid=self._eid(ct["name"]), name=ct["name"],
                t=ct.get("type", "unknown"), desc=ct.get("description", ""), p=self.project,
            )
            if ct.get("component"):
                s.run(
                    "MATCH (c:Component {name:$cn, project:$p}), "
                    "(ct:Contract {name:$ctn, project:$p}) "
                    "MERGE (c)-[:EXPOSES]->(ct)",
                    cn=ct["component"], ctn=ct["name"], p=self.project,
                )

    def _write_jms_queues(self, s, items: list[dict]):
        for q in items:
            s.run(
                "MERGE (n:JmsQueue {entityId:$eid}) "
                "SET n.name=$name, n.message_type=$mt, n.description=$desc, n.project=$p",
                eid=self._eid(q["name"]), name=q["name"],
                mt=q.get("message_type", ""), desc=q.get("description", ""), p=self.project,
            )
            for producer in q.get("producers", []):
                s.run(
                    "MATCH (c:Component {name:$cn, project:$p}), "
                    "(q:JmsQueue {name:$qn, project:$p}) "
                    "MERGE (c)-[:PRODUCES_TO]->(q)",
                    cn=producer, qn=q["name"], p=self.project,
                )
            for consumer in q.get("consumers", []):
                s.run(
                    "MATCH (c:Component {name:$cn, project:$p}), "
                    "(q:JmsQueue {name:$qn, project:$p}) "
                    "MERGE (c)-[:CONSUMES_FROM]->(q)",
                    cn=consumer, qn=q["name"], p=self.project,
                )

    def _write_interfaces(self, s, items: list[dict]):
        for iface in items:
            s.run(
                "MERGE (n:Interface {entityId:$eid}) "
                "SET n.name=$name, n.description=$desc, n.project=$p",
                eid=self._eid(iface["name"]), name=iface["name"],
                desc=iface.get("description", ""), p=self.project,
            )
            if iface.get("component"):
                s.run(
                    "MATCH (c:Component {name:$cn, project:$p}), "
                    "(i:Interface {name:$in, project:$p}) "
                    "MERGE (c)-[:EXPOSES]->(i)",
                    cn=iface["component"], **{"in": iface["name"]}, p=self.project,
                )

    # ── Markdown writers ───────────────────────────────────────────────────────

    def _write_value_streams_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Value Streams — {model.project_name}\n\n"]
        lines.append("| Value Stream | Description |\n|---|---|\n")
        for vs in model.value_streams:
            lines.append(f"| **{vs['name']}** | {vs.get('description','')} |\n")

        lines.append("\n## Capability Map\n\n")
        l1 = [c for c in model.capabilities if c.get("level") == "L1"]
        for cap in l1:
            lines.append(f"### {cap['name']} (L1)\n{cap.get('description','')}\n\n")
            l2s = [c for c in model.capabilities if c.get("parent") == cap["name"] and c.get("level") == "L2"]
            for l2 in l2s:
                lines.append(f"- **{l2['name']}** (L2): {l2.get('description','')}\n")
                l3s = [c for c in model.capabilities if c.get("parent") == l2["name"] and c.get("level") == "L3"]
                for l3 in l3s:
                    lines.append(f"  - {l3['name']} (L3): {l3.get('description','')}\n")
            lines.append("\n")

        (out / "value-streams.md").write_text("".join(lines))

    def _write_domains_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Domains — {model.project_name}\n\n"]
        for domain in model.domains:
            lines.append(f"## {domain['name']}\n{domain.get('description','')}\n\n")
            subs = [s for s in model.subdomains if s.get("domain") == domain["name"]]
            if subs:
                lines.append("| Subdomain | Type | Description |\n|---|---|---|\n")
                for sd in subs:
                    lines.append(f"| {sd['name']} | {sd.get('type','supporting')} | {sd.get('description','')} |\n")
            lines.append("\n")
        (out / "domains.md").write_text("".join(lines))

    def _write_capabilities_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Capabilities — {model.project_name}\n\n"]
        l1_caps = [c for c in model.capabilities if c.get("level") == "L1"]
        for cap in l1_caps:
            lines.append(f"## {cap['name']}\n_{cap.get('description','')}_\n\n")
            for l2 in [c for c in model.capabilities if c.get("parent") == cap["name"]]:
                lines.append(f"- **{l2['name']}** — {l2.get('description','')}\n")
                for l3 in [c for c in model.capabilities if c.get("parent") == l2["name"]]:
                    lines.append(f"  - {l3['name']} — {l3.get('description','')}\n")
            lines.append("\n")
        (out / "capabilities.md").write_text("".join(lines))

    def _write_bounded_contexts_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Bounded Contexts — {model.project_name}\n\n"]
        for bc in model.bounded_contexts:
            lines.append(f"## {bc['name']}\n")
            lines.append(f"**Subdomain**: {bc.get('subdomain','unknown')}\n\n")
            lines.append(f"{bc.get('description','')}\n\n")
            if bc.get("ubiquitous_language"):
                lines.append(f"**Ubiquitous Language**: {bc['ubiquitous_language']}\n\n")
            if bc.get("key_terms"):
                lines.append("**Key Terms**: " + ", ".join(bc.get("key_terms", [])) + "\n\n")
            lines.append("---\n\n")
        (out / "bounded-contexts.md").write_text("".join(lines))

    def _write_components_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Components — {model.project_name}\n\n"]
        lines.append("| Component | Type | Bounded Context | JMS Role | Description |\n|---|---|---|---|---|\n")
        for comp in sorted(model.components, key=lambda c: c.get("context", "") or ""):
            lines.append(
                f"| {comp['name']} | {comp.get('type','service')} | "
                f"{comp.get('context','—')} | {comp.get('jms_role','—')} | "
                f"{comp.get('description','')} |\n"
            )
        (out / "components.md").write_text("".join(lines))

    def _write_contracts_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Contracts & Interfaces — {model.project_name}\n\n"]
        by_comp: dict[str, list] = {}
        for ct in model.contracts:
            comp = ct.get("component", "unknown")
            by_comp.setdefault(comp, []).append(ct)

        for comp, cts in sorted(by_comp.items()):
            lines.append(f"## {comp}\n\n")
            lines.append("| Contract | Type | Description |\n|---|---|---|\n")
            for ct in cts:
                lines.append(f"| `{ct['name']}` | {ct.get('type','?')} | {ct.get('description','')} |\n")
            lines.append("\n")
        (out / "contracts.md").write_text("".join(lines))

    def _write_jms_topology_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# JMS Topology — {model.project_name}\n\n"]
        lines.append("> This documents the existing JMS message flows extracted from the legacy codebase.\n\n")
        lines.append("| Queue / Topic | Message Type | Producers | Consumers | Description |\n|---|---|---|---|---|\n")
        for q in model.jms_queues:
            producers = ", ".join(q.get("producers", [])) or "—"
            consumers = ", ".join(q.get("consumers", [])) or "—"
            lines.append(
                f"| `{q['name']}` | {q.get('message_type','?')} | "
                f"{producers} | {consumers} | {q.get('description','')} |\n"
            )
        lines.append("\n## Flow Diagram\n\n```mermaid\nflowchart LR\n")
        for q in model.jms_queues[:20]:
            qid = re.sub(r'\W+', '_', q['name'])
            lines.append(f'  {qid}["{q["name"]}"]\n')
            for prod in q.get("producers", [])[:3]:
                pid = re.sub(r'\W+', '_', prod)
                lines.append(f"  {pid} -->|produces| {qid}\n")
            for cons in q.get("consumers", [])[:3]:
                cid = re.sub(r'\W+', '_', cons)
                lines.append(f"  {qid} -->|consumed by| {cid}\n")
        lines.append("```\n")
        (out / "jms-topology.md").write_text("".join(lines))

    def _write_ubiquitous_language_md(self, model: DDDModel, out: Path):
        lines = [_MD_HEADER, f"# Ubiquitous Language — {model.project_name}\n\n"]
        lines.append("> Terms extracted per bounded context. Same term may have different meanings in different contexts.\n\n")
        for bc in model.bounded_contexts:
            if bc.get("key_terms") or bc.get("ubiquitous_language"):
                lines.append(f"## {bc['name']}\n\n")
                if bc.get("ubiquitous_language"):
                    lines.append(f"{bc['ubiquitous_language']}\n\n")
                if bc.get("key_terms"):
                    for term in bc.get("key_terms", []):
                        lines.append(f"- **{term}**\n")
                    lines.append("\n")
        (out / "ubiquitous-language.md").write_text("".join(lines))

    def _write_gaps_md(self, model: DDDModel, out: Path):
        lines = [
            _MD_HEADER,
            f"# Gap Analysis — {model.project_name}\n\n",
            "> Review each gap below. Change `Status` to `RESOLVED` or `ACCEPTED` before running `python main.py continue`.\n",
            "> - **RESOLVED**: You have confirmed the correct answer.\n",
            "> - **ACCEPTED**: You acknowledge the gap and want to proceed with the stated hypothesis.\n\n",
            f"**Total gaps**: {len(model.gaps)}\n\n---\n\n",
        ]
        for gap in model.gaps:
            lines.append(f"## {gap['id']} — {gap['description']}\n\n")
            lines.append(f"- **Status**: OPEN\n")
            lines.append(f"- **Confidence**: {gap.get('confidence', 50)}%\n")
            lines.append(f"- **Hypothesis**: {gap.get('hypothesis', 'Unknown')}\n")
            lines.append(f"- **Evidence needed**: {gap.get('evidence_needed', 'Manual review required')}\n")
            lines.append("\n---\n\n")
        (out / "gaps.md").write_text("".join(lines))

    def _write_decisions_md(self, model: DDDModel, out: Path):
        lines = [
            _MD_HEADER,
            f"# Decisions — {model.project_name}\n\n",
            "> Record architecture and design decisions made during gap review.\n",
            "> Reference gap IDs (e.g. GAP-001) in the Impact field.\n\n---\n\n",
            "## DEC-001 — [Your decision title here]\n\n",
            "- **Date**: \n",
            "- **Decision**: \n",
            "- **Rationale**: \n",
            "- **Impact**: \n\n",
            "---\n",
        ]
        (out / "decisions.md").write_text("".join(lines))


import re
